
server:
  port: 8480


#spring:
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true
#        username: root
#        password: windmagics

#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/test?allowMultiQueries=true
#spring.datasource.username=root
#spring.datasource.password=windmagics
#
## 主要是为了让框架扫描到mapper文件
#mybatis.mapper-locations=classpath*:/mapper/**Mapper.xml
##起别名。可省略写mybatis的xml中的resultType的全路径
#mybatis.type-aliases-package=com.windmagics.ssmdemo.model

##Spring
spring:
    application:
        name: test
#profile
    profiles:
        active: dev
#datasource
    datasource:
        # druid
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#mybatis
mybatis:
    mapper-locations: classpath*:/mapper/**Mapper.xml
    type-aliases-package: com.windmagics.ssmdemo.model
#    configuration-properties:
#      settings:
#          callSettersOnNulls：true
